import { AnimalType } from '@/types';

export const ANIMAL_TYPES: AnimalType[] = [
  'poultry', 'cattle', 'goats', 'sheep', 'pigs', 'rabbits', 'fish', 'bees', 'other',
];

export const ANIMAL_LABELS: Record<AnimalType, string> = {
  poultry: 'Poultry',
  cattle:  'Cattle',
  goats:   'Goats',
  sheep:   'Sheep',
  pigs:    'Pigs',
  rabbits: 'Rabbits',
  fish:    'Fish / Aquaculture',
  bees:    'Bees / Apiary',
  other:   'Other Animals',
};

export const ANIMAL_EMOJI: Record<AnimalType, string> = {
  poultry: '🐔',
  cattle:  '🐄',
  goats:   '🐐',
  sheep:   '🐑',
  pigs:    '🐷',
  rabbits: '🐇',
  fish:    '🐟',
  bees:    '🐝',
  other:   '🐾',
};

export const ANIMAL_BREEDS: Record<AnimalType, string[]> = {
  poultry:  ['Kienyeji / Indigenous', 'Kenbro', 'Rainbow Rooster', 'KARI Improved Kienyeji', 'Broiler (Cobb 500)', 'Broiler (Ross 308)', 'Layer (ISA Brown)', 'Layer (Lohmann Brown)', 'Ducks (Muscovy)', 'Turkeys', 'Quails', 'Other'],
  cattle:   ['Friesian / Holstein', 'Ayrshire', 'Jersey', 'Zebu (Boran)', 'Sahiwal', 'Angus', 'Crossbred', 'Other'],
  goats:    ['Galla', 'Boer', 'Toggenburg', 'Saanen', 'East African Goat', 'Crossbred', 'Other'],
  sheep:    ['Dorper', 'Suffolk', 'Red Maasai', 'Blackhead Persian', 'Merino', 'Crossbred', 'Other'],
  pigs:     ['Large White', 'Landrace', 'Duroc', 'Camborough', 'Crossbred', 'Other'],
  rabbits:  ['New Zealand White', 'California', 'Flemish Giant', 'Angora', 'Crossbred', 'Other'],
  fish:     ['Tilapia (Nile)', 'Tilapia (Blue)', 'Catfish', 'Trout', 'Other'],
  bees:     ['African Honeybee', 'East African Lowland Bee', 'Other'],
  other:    ['Local Breed', 'Improved Breed', 'Crossbred', 'Other'],
};

export const ANIMAL_PURPOSES: Record<AnimalType, string[]> = {
  poultry:  ['eggs', 'meat', 'dual_purpose', 'breeding'],
  cattle:   ['milk', 'meat', 'dual_purpose', 'breeding', 'draft'],
  goats:    ['milk', 'meat', 'dual_purpose', 'breeding'],
  sheep:    ['meat', 'wool', 'dual_purpose', 'breeding'],
  pigs:     ['meat', 'breeding'],
  rabbits:  ['meat', 'fur', 'breeding'],
  fish:     ['meat', 'breeding'],
  bees:     ['honey', 'wax', 'pollination'],
  other:    ['meat', 'mixed', 'other'],
};

export const ANIMAL_PURPOSE_LABELS: Record<string, string> = {
  eggs: 'Eggs', milk: 'Dairy / Milk', meat: 'Meat', dual_purpose: 'Dual Purpose',
  breeding: 'Breeding', draft: 'Draft / Work', wool: 'Wool', fur: 'Fur',
  honey: 'Honey', wax: 'Beeswax', pollination: 'Pollination', mixed: 'Mixed', other: 'Other',
};

export const ANIMAL_PRODUCTION_TYPES: Record<AnimalType, { value: string; label: string; units: string[] }[]> = {
  poultry:  [
    { value: 'eggs',   label: 'Eggs',            units: ['trays (30)', 'pieces', 'crates (360)'] },
    { value: 'meat',   label: 'Meat / Live Bird', units: ['kg', 'birds', 'pieces'] },
    { value: 'manure', label: 'Manure',           units: ['bags', 'kg', 'tons'] },
  ],
  cattle:   [
    { value: 'milk',   label: 'Milk',                 units: ['liters', 'kg'] },
    { value: 'meat',   label: 'Meat / Live Animal',   units: ['kg', 'animals'] },
    { value: 'manure', label: 'Manure',                units: ['bags', 'kg', 'tons'] },
  ],
  goats:    [
    { value: 'milk',   label: 'Milk',                 units: ['liters', 'kg'] },
    { value: 'meat',   label: 'Meat / Live Animal',   units: ['kg', 'animals'] },
  ],
  sheep:    [
    { value: 'meat',   label: 'Meat / Live Animal',   units: ['kg', 'animals'] },
    { value: 'wool',   label: 'Wool / Fleece',        units: ['kg'] },
  ],
  pigs:     [{ value: 'meat', label: 'Meat / Live Animal', units: ['kg', 'animals'] }],
  rabbits:  [{ value: 'meat', label: 'Meat / Live Rabbit', units: ['kg', 'animals'] }],
  fish:     [{ value: 'fish', label: 'Fish',               units: ['kg', 'pieces'] }],
  bees:     [
    { value: 'honey',  label: 'Honey',     units: ['kg', 'liters', 'jars (500g)'] },
    { value: 'wax',    label: 'Beeswax',   units: ['kg'] },
  ],
  other:    [{ value: 'other', label: 'Other Product', units: ['kg', 'units', 'liters'] }],
};

export const ANIMAL_EXPENSE_CATEGORIES: Record<AnimalType, { value: string; label: string; group: string }[]> = {
  poultry: [
    { value: 'day_old_chicks',    label: 'Day-Old Chicks',             group: 'Stock' },
    { value: 'stock_purchase',    label: 'Stock Purchase',             group: 'Stock' },
    { value: 'feed_starter',      label: 'Feed — Starter',             group: 'Feed' },
    { value: 'feed_grower',       label: 'Feed — Grower',              group: 'Feed' },
    { value: 'feed_finisher',     label: 'Feed — Finisher',            group: 'Feed' },
    { value: 'feed_layer',        label: 'Feed — Layer Mash',          group: 'Feed' },
    { value: 'feed_supplements',  label: 'Feed Supplements',           group: 'Feed' },
    { value: 'water',             label: 'Water Supply',               group: 'Feed' },
    { value: 'vaccination',       label: 'Vaccination',                group: 'Health' },
    { value: 'veterinary',        label: 'Veterinary Services',        group: 'Health' },
    { value: 'medicine',          label: 'Medicine / Drugs',           group: 'Health' },
    { value: 'deworming',         label: 'Deworming',                  group: 'Health' },
    { value: 'biosecurity',       label: 'Biosecurity / Disinfection', group: 'Health' },
    { value: 'housing_construction', label: 'Housing Construction',    group: 'Infrastructure' },
    { value: 'housing_maintenance',  label: 'Housing Maintenance',     group: 'Infrastructure' },
    { value: 'equipment',         label: 'Equipment',                  group: 'Infrastructure' },
    { value: 'labor_casual',      label: 'Labor — Casual',             group: 'Labor' },
    { value: 'labor_permanent',   label: 'Labor — Permanent',          group: 'Labor' },
    { value: 'electricity',       label: 'Electricity / Heating',      group: 'Utilities' },
    { value: 'transportation',    label: 'Transportation',             group: 'Logistics' },
    { value: 'slaughter',         label: 'Slaughter / Processing',     group: 'Logistics' },
    { value: 'other',             label: 'Other',                      group: 'Other' },
  ],
  cattle: [
    { value: 'stock_purchase',    label: 'Livestock Purchase',         group: 'Stock' },
    { value: 'fodder',            label: 'Fodder / Hay / Silage',      group: 'Feed' },
    { value: 'feed_concentrates', label: 'Feed Concentrates',          group: 'Feed' },
    { value: 'feed_supplements',  label: 'Mineral Supplements',        group: 'Feed' },
    { value: 'vaccination',       label: 'Vaccination',                group: 'Health' },
    { value: 'veterinary',        label: 'Veterinary Services',        group: 'Health' },
    { value: 'medicine',          label: 'Medicine / Drugs',           group: 'Health' },
    { value: 'deworming',         label: 'Deworming / Dipping',        group: 'Health' },
    { value: 'artificial_insemination', label: 'AI / Breeding',        group: 'Breeding' },
    { value: 'housing_construction', label: 'Shed Construction',       group: 'Infrastructure' },
    { value: 'labor_casual',      label: 'Labor — Casual',             group: 'Labor' },
    { value: 'labor_permanent',   label: 'Labor — Permanent',          group: 'Labor' },
    { value: 'milk_collection',   label: 'Milk Collection / Cooling',  group: 'Logistics' },
    { value: 'transportation',    label: 'Transportation',             group: 'Logistics' },
    { value: 'land_lease',        label: 'Pasture Lease',              group: 'Land' },
    { value: 'other',             label: 'Other',                      group: 'Other' },
  ],
  goats: [
    { value: 'stock_purchase',    label: 'Livestock Purchase',         group: 'Stock' },
    { value: 'fodder',            label: 'Fodder / Browse / Hay',      group: 'Feed' },
    { value: 'feed_concentrates', label: 'Feed Concentrates',          group: 'Feed' },
    { value: 'vaccination',       label: 'Vaccination',                group: 'Health' },
    { value: 'veterinary',        label: 'Veterinary Services',        group: 'Health' },
    { value: 'medicine',          label: 'Medicine / Drugs',           group: 'Health' },
    { value: 'deworming',         label: 'Deworming',                  group: 'Health' },
    { value: 'housing_construction', label: 'Housing Construction',    group: 'Infrastructure' },
    { value: 'labor_casual',      label: 'Labor — Casual',             group: 'Labor' },
    { value: 'transportation',    label: 'Transportation',             group: 'Logistics' },
    { value: 'other',             label: 'Other',                      group: 'Other' },
  ],
  sheep: [
    { value: 'stock_purchase',    label: 'Livestock Purchase',         group: 'Stock' },
    { value: 'fodder',            label: 'Fodder / Hay / Pasture',     group: 'Feed' },
    { value: 'vaccination',       label: 'Vaccination',                group: 'Health' },
    { value: 'veterinary',        label: 'Veterinary Services',        group: 'Health' },
    { value: 'deworming',         label: 'Deworming / Dipping',        group: 'Health' },
    { value: 'shearing',          label: 'Shearing',                   group: 'Production' },
    { value: 'labor_casual',      label: 'Labor — Casual',             group: 'Labor' },
    { value: 'transportation',    label: 'Transportation',             group: 'Logistics' },
    { value: 'other',             label: 'Other',                      group: 'Other' },
  ],
  pigs: [
    { value: 'stock_purchase',    label: 'Piglets / Weaners',          group: 'Stock' },
    { value: 'feed_starter',      label: 'Feed — Starter / Piglet',    group: 'Feed' },
    { value: 'feed_grower',       label: 'Feed — Grower',              group: 'Feed' },
    { value: 'feed_finisher',     label: 'Feed — Finisher',            group: 'Feed' },
    { value: 'feed_sow',          label: 'Feed — Sow Meal',            group: 'Feed' },
    { value: 'vaccination',       label: 'Vaccination',                group: 'Health' },
    { value: 'veterinary',        label: 'Veterinary Services',        group: 'Health' },
    { value: 'medicine',          label: 'Medicine / Drugs',           group: 'Health' },
    { value: 'deworming',         label: 'Deworming',                  group: 'Health' },
    { value: 'housing_construction', label: 'Pig Sty Construction',    group: 'Infrastructure' },
    { value: 'labor_casual',      label: 'Labor — Casual',             group: 'Labor' },
    { value: 'slaughter',         label: 'Slaughter / Processing',     group: 'Logistics' },
    { value: 'other',             label: 'Other',                      group: 'Other' },
  ],
  rabbits: [
    { value: 'stock_purchase',    label: 'Rabbit Purchase',            group: 'Stock' },
    { value: 'feed_pellets',      label: 'Feed Pellets',               group: 'Feed' },
    { value: 'fodder',            label: 'Hay / Green Fodder',         group: 'Feed' },
    { value: 'vaccination',       label: 'Vaccination',                group: 'Health' },
    { value: 'veterinary',        label: 'Veterinary Services',        group: 'Health' },
    { value: 'housing_construction', label: 'Hutch Construction',      group: 'Infrastructure' },
    { value: 'labor_casual',      label: 'Labor',                      group: 'Labor' },
    { value: 'other',             label: 'Other',                      group: 'Other' },
  ],
  fish: [
    { value: 'fingerlings',       label: 'Fingerlings / Seed Fish',    group: 'Stock' },
    { value: 'feed',              label: 'Fish Feed / Pellets',        group: 'Feed' },
    { value: 'pond_construction', label: 'Pond / Tank Construction',   group: 'Infrastructure' },
    { value: 'equipment',         label: 'Equipment',                  group: 'Infrastructure' },
    { value: 'water_treatment',   label: 'Water Treatment',            group: 'Water' },
    { value: 'veterinary',        label: 'Health / Veterinary',        group: 'Health' },
    { value: 'labor_casual',      label: 'Labor',                      group: 'Labor' },
    { value: 'electricity',       label: 'Electricity / Power',        group: 'Utilities' },
    { value: 'other',             label: 'Other',                      group: 'Other' },
  ],
  bees: [
    { value: 'colony_purchase',   label: 'Colony Purchase',            group: 'Stock' },
    { value: 'hive_purchase',     label: 'Hive Purchase',              group: 'Infrastructure' },
    { value: 'equipment',         label: 'Beekeeping Equipment',       group: 'Infrastructure' },
    { value: 'sugar_syrup',       label: 'Sugar Syrup / Feed',         group: 'Feed' },
    { value: 'veterinary',        label: 'Pest Control (Varroa)',       group: 'Health' },
    { value: 'processing',        label: 'Honey Processing',           group: 'Production' },
    { value: 'other',             label: 'Other',                      group: 'Other' },
  ],
  other: [
    { value: 'stock_purchase',    label: 'Livestock Purchase',         group: 'Stock' },
    { value: 'feed',              label: 'Feed',                       group: 'Feed' },
    { value: 'vaccination',       label: 'Vaccination',                group: 'Health' },
    { value: 'veterinary',        label: 'Veterinary Services',        group: 'Health' },
    { value: 'medicine',          label: 'Medicine',                   group: 'Health' },
    { value: 'deworming',         label: 'Deworming',                  group: 'Health' },
    { value: 'housing_construction', label: 'Housing Construction',    group: 'Infrastructure' },
    { value: 'labor_casual',      label: 'Labor',                      group: 'Labor' },
    { value: 'transportation',    label: 'Transportation',             group: 'Logistics' },
    { value: 'other',             label: 'Other',                      group: 'Other' },
  ],
};

export const COMMON_VACCINES: Record<AnimalType, string[]> = {
  poultry:  ['Newcastle Disease (ND)', 'Gumboro (IBD)', "Marek's Disease", 'Infectious Bronchitis (IB)', 'Fowl Typhoid', 'Fowl Pox', 'Avian Influenza (AI)', 'Coccidiosis', 'Other'],
  cattle:   ['Foot & Mouth Disease (FMD)', 'East Coast Fever (ECF)', 'Lumpy Skin Disease (LSD)', 'Blackquarter (BQ)', 'Anthrax', 'Brucellosis', 'Rift Valley Fever (RVF)', 'CBPP', 'Other'],
  goats:    ['PPR', 'CCPP', 'Foot & Mouth Disease (FMD)', 'Rift Valley Fever (RVF)', 'Anthrax', 'Blackquarter', 'Other'],
  sheep:    ['Foot & Mouth Disease (FMD)', 'Rift Valley Fever (RVF)', 'Anthrax', 'Blackquarter', 'Sheep Pox', 'Other'],
  pigs:     ['African Swine Fever (ASF)', 'Classical Swine Fever (CSF)', 'PCV2', 'Erysipelas', 'Other'],
  rabbits:  ['Rabbit Haemorrhagic Disease (RHD)', 'Myxomatosis', 'Pasteurellosis', 'Other'],
  fish:     ['Other'],
  bees:     ['Other'],
  other:    ['Other'],
};

export const HEALTH_EVENT_TYPES = [
  { value: 'vaccination',  label: 'Vaccination' },
  { value: 'treatment',    label: 'Treatment / Medication' },
  { value: 'checkup',      label: 'Vet Checkup' },
  { value: 'deworming',    label: 'Deworming / Dipping' },
  { value: 'birth',        label: 'Birth / Hatching' },
  { value: 'death',        label: 'Death / Loss' },
  { value: 'purchase',     label: 'Stock Purchase' },
  { value: 'sale',         label: 'Sale / Culling' },
  { value: 'transfer',     label: 'Transfer / Movement' },
  { value: 'other',        label: 'Other Event' },
];
